### ISSUE TITLE
RenderMarkupSection customisation

### ISSUE THREAD

**Issue by aduuub** [dailybeast/mobiledoc-react-renderer#2]
Hey, thanks for making this awesome library, we are very interested in using it. We noticed that there is currently no functionality for modifying the outputted markup elements. It would be great if there was a way to override the creation of elements using a passed in function that would return a JSX node. As an example it would be handy to take a function that overrides the creation of an h2 element and the clients returns an h4 with a className of 'u-textBold' which takes it's place. Cheers.

**Comment by Demven** [comment]
@aduuub Thanks for using our library and for your feedback! We'll look into this issue as soon as possible.

**Comment by Demven** [comment]
@aduuub We discussed your issue and here is the thing:
1) All sections (p, h1...h5 and others) are rendered by Mobiledoc as a simple tag with content inside. This is how Mobiledoc works. There is no way to pass some additional section data (like your class name 'u-textBlock') to the editor.toggleSection('h2') function (this is how you create the section?)
Check the Section class https://github.com/bustle/mobiledoc-kit/blob/master/src/js/models/_section.js
Only type is the valid argument for a section.
2) If you need to customize anything - use cards, atoms or markups. In your case it should be a card. To render card you use your own rendering function which returns html in any form you need it to be with all the classes and behavior you want.
