### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by talkingtab** [dailybeast/mobiledoc-react-renderer#3]
Can this be used with react-native or has anyone worked on how to integrate this with react-native?

**Comment by johnelliott** [comment]
Hey @talkingtab, we have not tried. Maybe @Demven can follow up.

**Comment by talkingtab** [comment]
I did find a draft-js render thing which might be a starting point for how to render mobiledoc, but I would love to have a mobiledoc input. Ghost.org also uses mobile doc and they have an android app which I am assuming renders mobiledoc.

**Comment by dfairaizl** [comment]
Hi @talkingtab. This render should work on react native but we can double check (it may need a few tweaks). I'll get back you as soon as I can!

**Comment by talkingtab** [comment]
@dfairaizl  Hey! thats great thanks so much.  I'm in the midst of building a react-native component and would love to use this! I'm new to mobiledocs and came here after seeing that ghost blog uses it. Any suggestions on where to start on getting a react-native mobiledocs editor or rolling my own?
